import {
  faAngleDown,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faAt,
  faBars,
  faBox,
  faBoxes,
  faBuilding,
  faCalendar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faComments,
  faCopy,
  faCode,
  faEllipsisH,
  faEnvelope,
  faEuroSign,
  faFile,
  faFilePdf,
  faFilter,
  faGlobe,
  faHashtag,
  faInfoCircle,
  faKey,
  faLink,
  faMapMarker,
  faMinus,
  faMoneyBill,
  faPencilAlt,
  faPhone,
  faPlus,
  faQuestion,
  faSadCry,
  faSearch,
  faSearchPlus,
  faShareAlt,
  faShoppingCart,
  faSignInAlt,
  faStore,
  faTachometerAlt,
  faThLarge,
  faTimes,
  faTrash,
  faTruck,
  faTv,
  faUser,
  faUserCircle,
} from "@fortawesome/free-solid-svg-icons";

import {
  faHeart as farHeart,
  faFileArrowUp as farFileArrowUp,
  faArrowDownToBracket as farArrowDownToBracket,
  faPhotoFilmMusic as farPhotoFilmMusic,
  faTriangleExclamation as farTriangleExclamation,
  faTrash as farTrash,
  faPencil as farPencil,
} from "@fortawesome/pro-regular-svg-icons";


export const FreeSolidIconSet = {
  faAngleDown,
  faAngleUp,
  faArrowLeft,
  faArrowRight,
  faAt,
  faBars,
  faBox,
  faBoxes,
  faBuilding,
  faCalendar,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faComments,
  faCopy,
  faCode,
  faEllipsisH,
  faEnvelope,
  faEuroSign,
  faFile,
  faFilePdf,
  faFilter,
  faHashtag,
  faGlobe,
  faInfoCircle,
  faKey,
  faLink,
  faMapMarker,
  faMinus,
  faMoneyBill,
  faPencilAlt,
  faPhone,
  faPlus,
  faQuestion,
  faSadCry,
  faSearch,
  faSearchPlus,
  faShareAlt,
  faShoppingCart,
  faSignInAlt,
  faStore,
  faTachometerAlt,
  faThLarge,
  faTimes,
  faTrash,
  faTruck,
  faTv,
  faUser,
  faUserCircle,
  farHeart,
  farFileArrowUp,
  farArrowDownToBracket,
  farPhotoFilmMusic,
  farTriangleExclamation,
  farTrash,
  farPencil
};
